[package]
name = "belay"
version = "0.1.0"
authors = ["Josh Mcguigan"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

[dev-dependencies]
assert_cmd = "0.12"
assert_fs = "0.13"
predicates = "1"
